language: generic
sudo: required
services:
    - docker

before_install:
    - docker build -t chappemj/docker-react -f Dockerfile.dev .

script:
    - docker run -e CI=true chappemj/docker-react npm run test
